<a href="https://colab.research.google.com/github/vamsivirigineni/Python-Data-Analysis/blob/main/Pandas/Pandas_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
#Series in pandas
sal = pd.Series([1000,1500,2000,2500,3000])
sal

0    1000
1    1500
2    2000
3    2500
4    3000
dtype: int64

In [5]:
# Name attribute in Series
age = pd.Series([20,25,30,35,40],name = 'age')
age

0    20
1    25
2    30
3    35
4    40
Name: age, dtype: int64

In [7]:
#Index in Series
age = pd.Series([20,21,22,23,24,25],index = ['sai','vamsi','sam','tarak','bob','bhAAi'],name="age")
age

sai      20
vamsi    21
sam      22
tarak    23
bob      24
bhAAi    25
Name: age, dtype: int64

In [9]:
#Operations on Series
movies = pd.Series(['paradise','endcore','varanasi','raaka','dragon'],name="movies")
movies

0    paradise
1     endcore
2    varanasi
3       raaka
4      dragon
Name: movies, dtype: object

In [12]:
#1)Indexing on Series
print(movies[0])
print(movies[4])
print(movies[3])

paradise
dragon
raaka

In [15]:
movies = pd.Series(['paradise','endcore','varanasi','raaka','dragon'],index=['nani','RDJ','BOB','AA','NTR'],name="movies")
movies

nani    paradise
RDJ      endcore
BOB     varanasi
AA         raaka
NTR       dragon
Name: movies, dtype: object

In [18]:
#indexing on series based on label
print(movies['nani'])
print(movies['NTR'])

paradise
dragon

In [19]:
#slicing on Series -> Indexing
print(movies[0:4])

nani    paradise
RDJ      endcore
BOB     varanasi
AA         raaka
Name: movies, dtype: object

In [20]:
print(movies[0:5])

nani    paradise
RDJ      endcore
BOB     varanasi
AA         raaka
NTR       dragon
Name: movies, dtype: object

In [21]:
print(movies[::2])

nani    paradise
BOB     varanasi
NTR       dragon
Name: movies, dtype: object

In [22]:
print(movies[1::2])

RDJ    endcore
AA       raaka
Name: movies, dtype: object

In [24]:
#slicing on series based on label
movies = pd.Series(['paradise','endcore','raaka','kaaka','salaar',"varanasi"],index=['nani','RDJ','AA','chiru','darling','bob'],name="movies")
movies

nani       paradise
RDJ         endcore
AA            raaka
chiru         kaaka
darling      salaar
bob        varanasi
Name: movies, dtype: object

In [25]:
print(movies['nani':'darling'])

nani       paradise
RDJ         endcore
AA            raaka
chiru         kaaka
darling      salaar
Name: movies, dtype: object

In [26]:
print(movies[:'AA'])

nani    paradise
RDJ      endcore
AA         raaka
Name: movies, dtype: object

In [ ]:
#Filtering on Series
#sysntax: var[condition]